/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as UbicacionesRouteImport } from './routes/ubicaciones'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as MovimientosRouteImport } from './routes/movimientos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const UbicacionesRoute = UbicacionesRouteImport.update({
  id: '/ubicaciones',
  path: '/ubicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimientosRoute = MovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/productos': typeof ProductosRoute
  '/proyectos': typeof ProyectosRoute
  '/solicitudes': typeof SolicitudesRoute
  '/ubicaciones': typeof UbicacionesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/productos': typeof ProductosRoute
  '/proyectos': typeof ProyectosRoute
  '/solicitudes': typeof SolicitudesRoute
  '/ubicaciones': typeof UbicacionesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/categorias': typeof CategoriasRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/movimientos': typeof MovimientosRoute
  '/productos': typeof ProductosRoute
  '/proyectos': typeof ProyectosRoute
  '/solicitudes': typeof SolicitudesRoute
  '/ubicaciones': typeof UbicacionesRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/categorias'
    | '/dashboard'
    | '/login'
    | '/movimientos'
    | '/productos'
    | '/proyectos'
    | '/solicitudes'
    | '/ubicaciones'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/categorias'
    | '/dashboard'
    | '/login'
    | '/movimientos'
    | '/productos'
    | '/proyectos'
    | '/solicitudes'
    | '/ubicaciones'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/categorias'
    | '/dashboard'
    | '/login'
    | '/movimientos'
    | '/productos'
    | '/proyectos'
    | '/solicitudes'
    | '/ubicaciones'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  CategoriasRoute: typeof CategoriasRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MovimientosRoute: typeof MovimientosRoute
  ProductosRoute: typeof ProductosRoute
  ProyectosRoute: typeof ProyectosRoute
  SolicitudesRoute: typeof SolicitudesRoute
  UbicacionesRoute: typeof UbicacionesRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubicaciones': {
      id: '/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/ubicaciones'
      preLoaderRoute: typeof UbicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimientos': {
      id: '/movimientos'
      path: '/movimientos'
      fullPath: '/movimientos'
      preLoaderRoute: typeof MovimientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  CategoriasRoute: CategoriasRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MovimientosRoute: MovimientosRoute,
  ProductosRoute: ProductosRoute,
  ProyectosRoute: ProyectosRoute,
  SolicitudesRoute: SolicitudesRoute,
  UbicacionesRoute: UbicacionesRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
